INSERT INTO schemes (scheme_key, name, sector, description, eligibility, benefit, apply_url, helpline, created_at, updated_at) VALUES
('pmkisan', 'PM Kisan Samman Nidhi', 'Agriculture', 'Income support of ₹6000/year to small and marginal farmers in 3 installments of ₹2000 each.', 'Small/marginal farmers with cultivable land, registered Aadhaar-linked bank account', '₹6,000 per year (₹2,000 every 4 months) directly in bank', 'https://pmkisan.gov.in/RegistrationForm.aspx', '155261', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('pmayg', 'PM Awas Yojana - Gramin', 'Housing', 'Financial assistance to rural BPL families to construct a pucca house.', 'Rural households without pucca house, listed in SECC 2011 survey, BPL ration card', '₹1.20 lakh (plains) or ₹1.30 lakh (hilly areas) in 3 installments', 'https://pmayg.nic.in', '1800-11-6446', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('nrega', 'MGNREGS (MNREGA)', 'Employment', 'Guarantees 100 days of wage employment per year to rural households.', 'Any adult member of rural household willing to do unskilled manual work', '100 days guaranteed work at ₹200-350/day, paid directly to bank', 'https://nrega.nic.in', '1800-345-22-44', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('pmjay', 'Ayushman Bharat PM-JAY', 'Health', 'World''s largest health insurance scheme — free hospital treatment up to ₹5 lakh per family.', 'Families listed in SECC 2011 database, BPL families, ASHA/Anganwadi workers', '₹5 lakh/year free treatment at empanelled hospitals (cashless)', 'https://beneficiary.nha.gov.in', '14555', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('nsp', 'National Scholarship Portal', 'Education', 'One-stop platform for SC/ST/OBC/Minority/disabled students to apply for central scholarships.', 'SC/ST/OBC/Minority students with family income below ₹2.5 lakh/year', '₹2,000 to ₹20,000 per year depending on course and category', 'https://scholarships.gov.in', '0120-6619540', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('pmuy', 'PM Ujjwala Yojana', 'Energy', 'Free LPG gas connection to BPL women to provide clean cooking fuel.', 'Women from BPL households above 18 years, no existing LPG connection in house', 'Free LPG connection + chulha (stove), subsidised refills', 'https://pmuy.gov.in', '1906', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('pmjdy', 'PM Jan Dhan Yojana', 'Financial Inclusion', 'Zero balance bank account for unbanked citizens with RuPay debit card and accident insurance.', 'Any Indian citizen above 10 years without a bank account', 'Zero-balance account + RuPay card + ₹2 lakh accident insurance + ₹10,000 overdraft', 'https://pmjdy.gov.in', '1800-11-0001', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('pmmvy', 'PM Matru Vandana Yojana', 'Women & Child', 'Cash incentive for pregnant and lactating women for first live birth.', 'Pregnant women above 19 years for first child, registered at Anganwadi', '₹5,000 in 3 installments (₹1000 + ₹2000 + ₹2000)', 'https://wcd.nic.in', '7998-799-804', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('mudra', 'PM Mudra Yojana', 'Employment', 'Loans for small business owners and entrepreneurs without collateral.', 'Non-farm small/micro enterprises, individual entrepreneurs, self-employed persons', 'Loans ₹50,000 (Shishu) to ₹10 lakh (Tarun) without collateral', 'https://mudra.org.in', '1800-180-1111', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('pmfby', 'PM Fasal Bima Yojana', 'Agriculture', 'Crop insurance scheme that protects farmers against natural calamities, pests, and diseases.', 'All farmers including sharecroppers and tenant farmers growing notified crops', 'Insurance coverage for crop loss — 80-90% of loss amount paid within 30 days', 'https://pmfby.gov.in', '1800-200-7710', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
